### ISSUE TITLE
"[x] is a First Mate since NaN years ago"

### ISSUE THREAD

**Issue by iantowns** [joostdecock/site#403]
This is a pretty minor issue, but it looks like the patron page isn't showing time as patron for anybody.

<img width="1185" alt="screen shot 2018-05-25 at 9 13 48 am" src="https://user-images.githubusercontent.com/8238540/40546038-018a1262-5ffc-11e8-9a24-4b3c77654b3a.png">

**Comment by joostdecock** [comment]
Well spotted 👍

**Comment by joostdecock** [comment]
fixed
