### ISSUE TITLE
Links in freesewing.org/i18n/ to GitHub translation files broken

### ISSUE THREAD

**Issue by AlfaLyr** [joostdecock/site#406]
The links in freesewing.org/i18n/ that point to edit the translation files are broken. They point to some address with "v2" in it, and maybe since the site is already out it doesn't have the "v2" anymore.

**Comment by joostdecock** [comment]
You are 100% correct. So are you ready to become more than a translator and fix it? 😃

**Comment by AlfaLyr** [comment]
Done! (I think)
