### ISSUE TITLE
Patron banner appearing for non-patron

### ISSUE THREAD

**Issue by apostrophes** [joostdecock/site#412]
<img width="1189" alt="screen shot 2018-05-25 at 9 54 07 pm" src="https://user-images.githubusercontent.com/39636205/40571518-30b6dd2e-6068-11e8-9cf2-552429ef3a60.png">

I haven't actually given you any money, so you probably don't want to be thanking me

**Comment by joostdecock** [comment]
Maybe this is some sort of elaborate reverse-psychology on our behalf? :rofl: 

I'll look into it
