### ISSUE TITLE
Saving changes to model gives "error-undefined"

### ISSUE THREAD

**Issue by apostrophes** [joostdecock/site#413]
This seems to be the case for any model field. This is an existing model (rmxzk, I can't share it for obvious reasons):

<img width="1206" alt="screen shot 2018-05-25 at 10 34 14 pm" src="https://user-images.githubusercontent.com/39636205/40571712-c7f85322-606b-11e8-932b-7557b5725d41.png">
<img width="1195" alt="screen shot 2018-05-25 at 10 28 51 pm" src="https://user-images.githubusercontent.com/39636205/40571669-4c0b97ce-606b-11e8-8138-4e3f3932e187.png">
<img width="1189" alt="screen shot 2018-05-25 at 10 29 30 pm" src="https://user-images.githubusercontent.com/39636205/40571670-4c17c116-606b-11e8-9040-be81d405b942.png">
<img width="1186" alt="screen shot 2018-05-25 at 10 29 43 pm" src="https://user-images.githubusercontent.com/39636205/40571671-4c2482fc-606b-11e8-89f1-f4f4d4b5cc90.png">

I'm trying to create a new model and see if that changes the issue, but it's now been loading for over a minute, so I think that functionality may also be encountering problems?

**Comment by joostdecock** [comment]
This one was due to a database field we missed in our migration script. Fixed now.
