### ISSUE TITLE
Updating Settings field resets Units setting

### ISSUE THREAD

**Issue by apostrophes** [joostdecock/site#414]
This has occurred on every Settings field I've tried. It also resets the theme back to classic. I'm not sure whether any other fields are affected. 

<img width="939" alt="screen shot 2018-05-25 at 10 38 35 pm" src="https://user-images.githubusercontent.com/39636205/40571759-b47a7856-606c-11e8-93ad-b67a7a52a1cf.png">
--
<img width="952" alt="screen shot 2018-05-25 at 10 38 45 pm" src="https://user-images.githubusercontent.com/39636205/40571760-b48b9e38-606c-11e8-849b-4387dc6b5cad.png">

**Comment by apostrophes** [comment]
(please let me know if you'd prefer I stick to high-priority issues or otherwise hold back given the current volume of site changes, I don't want to get annoying but was in a testing kind of mood)

**Comment by joostdecock** [comment]
I really appreciate you doing this. Sure, it doesn't make me feel great to see all these problems pile up, but it's the first step towards getting them fixed, so please continue.

**Comment by joostdecock** [comment]
FIxed in data v2.0.1
