### ISSUE TITLE
Links in MarkDown content cause a page reload

### ISSUE THREAD

**Issue by joostdecock** [joostdecock/site#419]
Links added through a *nuxt-link* component don't reload the page, but rather fetch the content in SPA mode.

This is not the case for links in the MarkDown content that are loaded via NuxtDown. Would be nice if that was possible.

**Comment by berce** [comment]
According to the answer by Atinux to [an issue at nuxt-community](https://github.com/nuxt-community/modules/issues/185) about getting nuxt-links working in markdown, the documentation pages of nuxt use [this solution](https://github.com/nuxt/nuxtjs.org/blob/master/components/HtmlParser.vue).

I hope it makes sense to you and is all the help you need.

**Comment by joostdecock** [comment]
Thank you very much @berce great tip! I'll be looking in to it 👍

**Comment by joostdecock** [comment]
I lost track of this issue, but this is fixed in the new site we're working on. So I'm closing this.
