### ISSUE TITLE
"e.data.measurements is undefined" when drafting pattern

### ISSUE THREAD

**Issue by joostdecock** [joostdecock/site#433]
@sewmalina reported this on gitter:

So I go into my profile --> draft --> new draft and then select any pattern (let's say simon). Then I land on the link https://freesewing.org/draft/simon and the page is empty except for the error message and "Add comment" and "Become a patron" buttons

**Comment by sewmalina** [comment]
Root cause has probably something to do with missing consent for model data (somehow I missed to give my consent) but was not resolved after giving consent to processing model data.

Created another account and got it working on the same device so this is account-related.

**Comment by joostdecock** [comment]
Can I know your freesewing username. I need it to reproduce this. Tx

**Comment by sewmalina** [comment]
Yes sure, it's sew.malina :-)

2018-05-29 16:33 GMT+02:00 Joost De Cock <notifications@github.com>:

**Comment by joostdecock** [comment]
![sewmalina](https://user-images.githubusercontent.com/1708494/40668581-32fb7c3e-6365-11e8-86e8-559c62fe4c84.png)

Thank you. I was able to reproduce it. Now all I have to do is fix it ;)

**Comment by joostdecock** [comment]
Fixed in v2.0.10. Thanks for reporting this and sorry for the wait.
