### ISSUE TITLE
Background on login page

### ISSUE THREAD

**Issue by berce** [joostdecock/site#441]
There's hardly any contrast between the font color of the username and the background picture at the login page.

**Comment by joostdecock** [comment]
Could you clarify what exactly you mean. Is the username in the form not clear:

![username1](https://user-images.githubusercontent.com/1708494/40662143-d442df34-6355-11e8-898c-e445551cabc0.PNG)

Or is the username in the menu not clear:

![username2](https://user-images.githubusercontent.com/1708494/40662153-db8f2518-6355-11e8-8cf6-c3237b5c3dac.png)

**Comment by berce** [comment]
For me there's no white transparent background.
![login-no-white-background](https://user-images.githubusercontent.com/10439709/40662684-5fce8e44-6357-11e8-8318-b16d7b8bf775.jpg)

I 'm using Qutebrowser in Nixos. I think it's based on Chromium.
Now I tested with Firefox and Chromium and it looks like your screenshots. No need to fix this for my exotic case.

**Comment by joostdecock** [comment]
Can you check this jsfiddle to see if there's a difference between the two boxes: https://jsfiddle.net/qut8uuxj/

**Comment by joostdecock** [comment]
![fiddle](https://user-images.githubusercontent.com/1708494/40663748-acbddcee-6359-11e8-913a-455fbb8abcbd.png)

This is what I see

**Comment by berce** [comment]
The rgba() notation works as expected.
![qutebrowser-color_notation_difference](https://user-images.githubusercontent.com/10439709/40682867-210b597c-638d-11e8-8918-cde5e307cb5e.jpg)

**Comment by joostdecock** [comment]
Ok, thanks for confirming that. I've switched to rgba() notation, so this should be fixed now.
