### ISSUE TITLE
Drafting Simon

### ISSUE THREAD

**Issue by nutation** [joostdecock/site#454]
I get a broken image when I attempt to draft simon with a baseball hem

[freesewing.org.pdf](https://github.com/freesewing/site/files/2056516/freesewing.org.pdf)

**Comment by joostdecock** [comment]
Thank you for reporting this. This is due to the hemStyle option being passed by name rather than key. I'll implement a fix ASAP.

**Comment by joostdecock** [comment]
This has been fixed in v2.0.11

That being said, I've created issues #456 and #456 to deal with some outstanding issues with imperial units.

**Comment by nutation** [comment]
Wow! you are amazing
