### ISSUE TITLE
Extra SA option that doesn't look like it belongs there

### ISSUE THREAD

**Issue by joostdecock** [joostdecock/site#458]
![sa](https://user-images.githubusercontent.com/1708494/40784086-d18b16b8-64e4-11e8-95a9-de874dfa3de3.png)

Reported by the rising star in freesewing land: @AlfaLyr

**Comment by AlfaLyr** [comment]
I think it's solved ;)

**Comment by joostdecock** [comment]
So do I :) I'll keep this open until it's deployed on the website
