### ISSUE TITLE
Add missing images for pattern options

### ISSUE THREAD

**Issue by joostdecock** [joostdecock/site#466]
- elasticWidth option for bruce
 - bicepsease for hugo
 - hemstyle for wahid
 - adjustment ribbon for benjamin
 - and all options for brian

**Comment by AlfaLyr** [comment]
I love illustrating, so if you give me some source files (svg I guess) and/or some guidelines I can help with this :)

**Comment by joostdecock** [comment]
Now you tell me? After I spent the last 5 days making illustrations? :)

The images are here: https://github.com/freesewing/site/tree/develop/nuxt/static/img/patterns

Some guidance:

**elasticWidth option for bruce**

Start from the bruce linedrawing, put 2 fronts next to each other, and make the elastic wider in one of them. A bit like the waistband width in theo(dore).

**bicepsease for hugo**

Start from the hugo linedrawing, put 2 fronts next to each other, and add arrows you can steal from the bicepsease option in Bent

**hemstyle for wahid**

Start from the wahid linedrawing, put 2 fronts next to each other, and on one of them change the hem to be rounded. You can copy this from the hemradius illustration.

**adjustment ribbon for benjamin** 

@woutervdub used a picture for this, and I'm not certain how to illustrate it. You do you.

**all options for brian**

It seems I somehow forgot about this. So starting from the brian linedrawing, we need an illustration for all options. The illustrations from sven should be a good guideline.



Perhaps it's best to start with the brian illustrations, because I think I might have the others somewhere and just forgot to copy them in the right place. I'll check later this morning and get back to you.

**Comment by AlfaLyr** [comment]
I told you when you opened the issue :p
Where do I upload the stuff? Should I just email it to you?

**Comment by joostdecock** [comment]
I've found the missing images for Bruce, Wahid, and Hugo. The ones for Benjamin and Brian I don't have.

You add them to your repository, then you submit a pull request :) It's not different from changes to code or translations. Let me know if you need any help with that.

**Comment by AlfaLyr** [comment]
Okie dokie. Do you want the SVGs or PNGs of certain resolution instead?

**Comment by joostdecock** [comment]
Only SVGs. That makes future changes a lot easier, and looks great on all screens :)

**Comment by AlfaLyr** [comment]
Good! I'm updating my repository, so if you see weird pull requests from me it's just that I'm doing stuff wrong, just ignore them xD

**Comment by AlfaLyr** [comment]
I did the ones that are the same in Sven, and I'll do the others later. I think I did the pull request right, there should be 6 images.
