### ISSUE TITLE
Hover text for badges

### ISSUE THREAD

**Issue by AlfaLyr** [joostdecock/site#474]
I'll try to set the name of the badge as the "title" attribute of the badge images in the user's profiles, so the name appears when you hover over them.

I think it's just me, but it annoys me that I have to look at the source of the page if I want to know what a badge means :P

**Comment by joostdecock** [comment]
We might need to add the badge names and descriptions to a YAML file for translation, if we want to do this right. Thoughts?

**Comment by AlfaLyr** [comment]
True :)
I just pulled something but I don't know if I did it right, and no translation support. I still don't know completely how those YAML files work, but I'll look into it!
