### ISSUE TITLE
Error when selecting button & button hole pattern to be print

### ISSUE THREAD

**Issue by Djadji** [joostdecock/site#562]
Thanks for reporting an issue. Please keep in mind that:

 - Problems with patterns are for the [core](https://github.com/freesewing/core/issues/new) repository
 - Website issues are for the [site](https://github.com/freesewing/site/issues/new) repository
 - Problems with the data backend are for the [data](https://github.com/freesewing/data/issues/new) repository

**Comment by joostdecock** [comment]
Could you elaborate a bit on what exactly the problem is?

**Comment by joostdecock** [comment]
Stale. Closing
