### ISSUE TITLE
Problems consent signing up

### ISSUE THREAD

**Issue by MathildeD7** [joostdecock/site#564]
Thanks for reporting an issue. Please keep in mind that:

 - Problems with patterns are for the [core](https://github.com/freesewing/core/issues/new) repository
 - Website issues are for the [site](https://github.com/freesewing/site/issues/new) repository
 - Problems with the data backend are for the [data](https://github.com/freesewing/data/issues/new) repository

**Comment by joostdecock** [comment]
Seems like our backend SSL certificate expired. I'll fix this ASAP

**Comment by joostdecock** [comment]
Ok, fixed. Thanks for reporting this.

**Comment by MathildeD7** [comment]
Of course. Thanks for fixing it quickly!
