### ISSUE TITLE
Sandy draft doesn't work

### ISSUE THREAD

**Issue by annekecaramin** [joostdecock/site#574]
![schermafbeelding 2018-08-01 om 21 14 32](https://user-images.githubusercontent.com/38046191/43541564-39cdebd2-95ba-11e8-9db6-a29e1aafc02f.png)

:(

**Comment by joostdecock** [comment]
Hmm, this fails when fetching the draft from core, but it works fine when I run the same request individually 🤔

I might need coffee before I can fix this.

**Comment by joostdecock** [comment]
Turned out to be a problem with the sampler config of Sandy. Fixed in core v1.10.1 which has been deployed in production.

Long story short, it should work now.
