### ISSUE TITLE
showcase broken links (it was: "merge user")

### ISSUE THREAD

**Issue by ericamattos** [joostdecock/site#582]
https://freesewing.org/users/ecmtts

this is me! :)

"ecmtts" should be merged with "ericamattos" profile

....

Thanks for reporting an issue. Please keep in mind that:

 - Problems with patterns are for the [core](https://github.com/freesewing/core/issues/new) repository
 - Website issues are for the [site](https://github.com/freesewing/site/issues/new) repository
 - Problems with the data backend are for the [data](https://github.com/freesewing/data/issues/new) repository

**Comment by joostdecock** [comment]
What exactly do you mean by merged?
Also, https://freesewing.org/users/ecmtts doesn't seem to exist?

**Comment by ericamattos** [comment]
Hi Joost! Sorry for the confusion! It's just a broken link of the user in this showcase info https://freesewing.org/showcase/matching-simon

**Comment by ericamattos** [comment]
I think some other showcase pages have broken links for the user. for instance: https://freesewing.org/showcase/speckles-simon , https://freesewing.org/showcase/wonder-woman-simon , https://freesewing.org/showcase/simon-on-snook

**Comment by joostdecock** [comment]
Seems I never got around to changing the Jekyll includes to native MarkDown.
Thanks for reporting this, I've updated it. It will be deployed soon.
