### ISSUE TITLE
Template includes have broken

### ISSUE THREAD

**Issue by cblgh** [joostdecock/site#597]
The includes over at https://freesewing.org/docs/patterns/notation appear to have broken. 

(Probably as part of the [tech upgrade](https://freesewing.org/blog/announcing-freesewing-library)? :)

![](https://i.cblgh.org/2018-08/2561q95.png)

**Comment by joostdecock** [comment]
This is actually a Jekyll include that hasn't been updated. But that change dates back to the end of May 🙄
The new code I wrote about recently isn't used on the site yet.

That being said, that k you for reporting this. I will find some time this weekend to fix it.

**Comment by cblgh** [comment]
🔥
