### ISSUE TITLE
Error Creating pattern 

### ISSUE THREAD

**Issue by emmakolade** [joostdecock/site#619]
Thanks for reporting an issue. Please keep in mind that:

 - Problems with patterns are for the [core](https://github.com/freesewing/core/issues/new) repository
 - Website issues are for the [site](https://github.com/freesewing/site/issues/new) repository
 - Problems with the data backend are for the [data](https://github.com/freesewing/data/issues/new) repository

**Comment by joostdecock** [comment]
Hmm, not certain what is causing this, but I will look into it and report back here.

**Comment by joostdecock** [comment]
Ok, so I had a look at this, and it seems to me that you need to have a look at your measurements, for they are most likely incorrect.

Please have a look at the measurement instructions here: https://freesewing.org/docs/measurements

Assuming your hip circumference of 41" is correct, I'd say that:

 - It is very unlikely that your hip to upper leg measurement is 13.5"
 - It seems impossible that your upper leg circumference is 13"

The measurements you entered seem impossible. As such, it's impossible to draft a pattern for them.

**Comment by emmakolade** [comment]
Hey Joost..thank you so much..
What is the standard upper leg measurement..

**Comment by emmakolade** [comment]
My upper leg Circumference is 26" I made a mistake..  I will go back and
retry..  Thank you so much you are amazing
