### ISSUE TITLE
Unable to signin up

### ISSUE THREAD

**Issue by Loggss** [joostdecock/site#631]
Hello,

We can not sign up to the website. Apparently, this thing was already described few weeks ago in a previous issue.

Do you have any idea to solve it ?

Thanks

**Comment by joostdecock** [comment]
Given that someone signed up less than 10 minutes ago, this is not a general issue, but perhaps something that affects you for some specific reason.

Would you be able to clarify what the problem is? Is it that you did not receive the email, or something else?

**Comment by ninja-fire** [comment]
Hi, i have the same problem
I already have an account and when i want to log in it's impossible, the page never stop loading 
i also tried to create a new account but this message comes out 
![capture](https://user-images.githubusercontent.com/44232936/47087560-9d9c8d00-d21c-11e8-8209-bea375a0d453.JPG)

**Comment by joostdecock** [comment]
Can you share your username so I can have a look, because things look normal from here.
