### ISSUE TITLE
Please allow sign-in with Google Auth

### ISSUE THREAD

**Issue by wt** [joostdecock/site#643]
Hi there, it would be super awesome if I could tie my Google account to my account for freesewing so that I could login without yet another password.

Here's a link for info: https://developers.google.com/identity/sign-in/web/sign-in

Other SSOs would also probably be handy.

BTW, I really love the site. Thanks for putting this together.

**Comment by joostdecock** [comment]
As we're working on a new frontend, this one is feature frozen. As such this won't be implemented here.

However, feel free to create an issue here for this feature: https://github.com/freesewing/website/issues/new
