### ISSUE TITLE
not getting signup activation email but getting github signup straight away

### ISSUE THREAD

**Issue by lilyh01** [joostdecock/site#645]
Thanks for reporting an issue. Please keep in mind that:

 - Problems with patterns are for the [core](https://github.com/freesewing/core/issues/new) repository
 - Website issues are for the [site](https://github.com/freesewing/site/issues/new) repository
 - Problems with the data backend are for the [data](https://github.com/freesewing/data/issues/new) repository

**Comment by joostdecock** [comment]
We had an issue causing outgoing emails to queue. It's been resolved now, and you should have received the emails.

Thanks for reporting this.
